#!/bin/bash

set -euo pipefail

# Nginx listens on 10000 (Render's PORT), so internal services use fixed ports
export NGINX_PORT="${PORT:-10000}"
export PORT=3000
export NUXT_PORT=3000

export BASEROW_PUBLIC_URL="${RENDER_EXTERNAL_URL:-}"
export BASEROW_CADDY_ADDRESSES=":${NGINX_PORT}"
export REDIS_URL=${REDIS_TLS_URL:-$REDIS_URL}
export DJANGO_SETTINGS_MODULE='baserow.config.settings.heroku'
export BASEROW_RUN_MINIMAL=yes
export DISABLE_EMBEDDED_PSQL=yes
export DISABLE_EMBEDDED_REDIS=yes
export BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION=${BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION:-true}
export MIGRATE_ON_STARTUP="${MIGRATE_ON_STARTUP:-}"
export DISABLE_VOLUME_CHECK=yes

export BASEROW_AMOUNT_OF_WORKERS=${BASEROW_AMOUNT_OF_WORKERS:-1}
export BASEROW_AMOUNT_OF_GUNICORN_WORKERS=${BASEROW_AMOUNT_OF_GUNICORN_WORKERS:-$BASEROW_AMOUNT_OF_WORKERS}

export EMAIL_SMTP="false"
DOCKER_USER=$(whoami)
export DOCKER_USER
export BASEROW_CADDY_USER="${BASEROW_CADDY_USER:-$DOCKER_USER}"
